0:
	cp files/0-main.c .
	gcc -Wall -Wextra -Werror -pedantic -o 0-slide_line 0-main.c 0-slide_line.c
	rm 0-main.c
	./0-slide_line L 2 2 0 0
	./0-slide_line L 2 2 0 0 0 0 0 2 0 0 0 2 0 4
	./0-slide_line R 2 2 2 2
	./0-slide_line R 2 2 2 2 2
	./0-slide_line L 2 4 8 16
	./0-slide_line R 2 4 8 16
	./0-slide_line R 4 4 8 16
	
	rm 0-slide_line

betty:
	betty *.c *.h
